### ISSUE TITLE
replace `pgvector` with `timescaledb`

### ISSUE THREAD

**Issue by avelino** [talkdai/dialog#11]
improving vector performance [ref](https://www.timescale.com/blog/how-we-made-postgresql-the-best-vector-database/
)

https://www.timescale.com/ai

**Comment by lgabs** [comment]
Its seems a very nice vectordb, but given the dozens of free vectordbs available  in langchain intergrations ([including timescale](https://python.langchain.com/docs/integrations/vectorstores/timescalevector/)) and given that timescale is [not free](https://www.timescale.com/pricing) and not self-hosted as of now, we'd better maintain postgres as a wide known choice, I think.

**Comment by vmesel** [comment]
@lgabs i agree. I'll close this issue as we are not going to support this right now.
