### ISSUE TITLE
knowledge base behavior can create confusion

### ISSUE THREAD

**Issue by lgabs** [talkdai/dialog#140]
### Current Behavior
Currently, when starting the dialog service for the first time, it populates the vector store with embeddings from the specified CSV path. During this process, it creates a unique key for each CSV entry by concatenating certain column fields and applying a hash function to them. If the service is restarted after the CSV has been updated, it attempts to update only the entries with new hashes.

### Issue
This behavior may be problematic because the CSV typically represents the entire knowledge base to be considered and should not be mixed with past entries already in the vector database during updates. For example, if we have an entry Q&A:

```
Question: Until when can I cancel my order?
Answer: You can cancel your order up to 3 hours before the trip.
```
and the team responsible for maintaining the knowledge base changes this to 1 hour, the new entry will be stored in the database along with the old information, resulting in duplicate and potentially conflicting entries.

### Suggested Improvement
Upon starting the dialog service, delete the existing collection) and create a new one with the contents of the current CSV. Providing an option for updating may be beneficial if retaining every entry indefinitely is not a problem. This would demand changes in `load_csv.py`.

**Comment by avelino** [comment]
today a **diff** is made of what is in the `CSV` (knowledge base) with the records that are in the database, keeping the existing ones and inserting the non-existent ones.

**We don't *"delete"* the non-existent ones: I want to remove the records that no longer exist in the CSV.

We could have an option in `load_csv.py` to reset the database before populating the database with the knowledge base (CSV).

`--clear-db` might be a good name
