### ISSUE TITLE
Embedding is not ocurring over question and document together

### ISSUE THREAD

**Issue by lgabs** [talkdai/dialog#145]
Currently, we're only embedding the content from knowledge base:
https://github.com/talkdai/dialog/blob/f97728a06883d3deeb1e1af58006be0fd92b56ef/src/load_csv.py#L57

However, is it a better practice to embed  both question and answer together, as the retrieval will compare the user question over documents and they should have questions as well for better context. Maybe we can explain that in the documentation, to achieve that, `content` should be the question (which is already a column) concatenated with the answer, or if we keep the word `content` reserved for answers, we join question and answer in code.

### Suggestion
I think we should change the term `content` to `document` (maintaining compatibility, but langchain treat each unit of knowledge base as _document_, so it'd be good to align with that) and explain in our documentation that this will be the main input for embeddings (other columns will act as metadata). We cal also give an example of Q&A document "Question: ... Answer: ..." to give more clarity (if the user want to embed just answers, he/she prepares a csv with answer in `document` column)

**Comment by avelino** [comment]
the change makes sense to maintain the langchain standard.

@lgabs checking for the column "document" and seeking the column "content" ensures compatibility while making the alteration.

**Comment by lgabs** [comment]
Good, you can assign that to me

**Comment by lgabs** [comment]
I'll wait #147 first

**Comment by vmesel** [comment]
@lgabs can I close this issue?
