### ISSUE TITLE
Add support for multiple LLMs

### ISSUE THREAD

**Issue by vmesel** [talkdai/dialog#154]
Adding support for multiple LLMs would make it easier to build agents that require more abstraction or more inputs from different models. We could implement this using the same behavior as Django uses for settings databases, which is basically a dictionary of databases.

We need to think on how to implement this.

```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}
```

One way we could make this work is by using the `get_llm_class(llm_name)` passing the LLM name. This could be loaded inside the toml or another config method.

**Comment by avelino** [comment]
@vmesel duplicate?
https://github.com/talkdai/dialog/issues/194

**Comment by vmesel** [comment]
#198 is also a duplicate, but will keep it there as it has more context on the approach done right now.
