### ISSUE TITLE
Add support to LangServe with FastAPI

### ISSUE THREAD

**Issue by avelino** [talkdai/dialog#170]
https://python.langchain.com/docs/langserve

> This library is integrated with [FastAPI](https://fastapi.tiangolo.com/) and uses [pydantic](https://docs.pydantic.dev/latest/) for data validation.

talkd/dialog uses LangChain and we probably won't switch frameworks. Given this statement, it's important to follow the evolution of LangChain and the projects they maintain to keep up to date.

**warning:** I know that LangChain is a new project and will have updates that break our implementations. That's fine, it's part of our choice to use LangChain - we'd have this kind of problem using another framework.

## proposal
With the above context in mind, it makes sense to swap the FastAPI us for the LangServer abstraction (which uses FastAPI underneath).

## premise

we can't break the signatures of the current endpoints
we can have other endpoints and warn those who are using the old one to switch to the new one, but at this point we can't break what works

**Comment by vmesel** [comment]
Awesome @lgabs, thanks for helping with that!

Let's make it as our second stable release of the project so we have the benefits of the langserver as well. 🚀

**Comment by vmesel** [comment]
@avelino and @lgabs do you guys know if we can keep our current source code and just swap the server library? Would this be a good starting point to move this needle to this new version?

**Comment by lgabs** [comment]
@vmesel I thought about the implementation and checked some examples and as far as I know it should be possible to follow the proposal while keeping the premise, exposing new endpoints without breaking current ones. I'll focus on that in following days to bring some ideas here 🦜

**Comment by vmesel** [comment]
Awesome @lgabs, thanks for the feedback! I'm looking forward to this. Let's do this implementation in small chunks so we are able to make it less impactful through version changes.
