### ISSUE TITLE
improve prompt (logic) for not identifying as AI - "Peço desculpas, mas como assistente de IA"

### ISSUE THREAD

**Issue by avelino** [talkdai/dialog#18]
**QA:** qual telefone de compra pelo whatsapp?
**answer:** Peço desculpas, mas como assistente de IA, não tenho acesso a informações atualizadas em tempo real. Recomendo que você verifique o número de telefone atualizado para compras pelo WhatsApp no site oficial da Buser ou entre em contato com o suporte da empresa para obter essa informação.

![Screenshot 2023-11-18 at 08 35 57](https://github.com/talkdai/dialog/assets/31996/f47ff88c-0fc6-482d-bd66-f0cae6fca334)

**Comment by vmesel** [comment]
Maybe this is easily solvable by adding a default fallback message.

**Comment by vmesel** [comment]
@avelino just deployed a change on this. I've added to the embedding a new text explaining who is the bot.
