### ISSUE TITLE
embedding: regenerate and popularize vector when changing scope

### ISSUE THREAD

**Issue by avelino** [talkdai/dialog#19]
our csv has the following fields:
- category
- subcategory
- question
- content

we can use the first 3 fields as a "key", making it simpler to know which embedding we need to rewrite and which we need to delete (if it is removed from the csv).

**Comment by vmesel** [comment]
So as far as I understood, we already do this partially on the load_csv.py file.

```python
df = df[~df["question"].isin(df_in_db["question"])] # https://github.com/talkdai/dialog/blob/main/src/load_csv.py#L24
```

Basically, we would change this logic to use these 3 fields in order to generate a PK and then, if any PK is not matched, insert it into the database, right?
