### ISSUE TITLE
[docs] Show an image of dialog architecture in README

### ISSUE THREAD

**Issue by lgabs** [talkdai/dialog#196]
**Idea:** Sometimes images can really help the understanding of software architectures. Since dialog deals with two projects (dialog and dialog-lib) + optional plugins, it seems like a good idea to show a picture of our architecture in README. I've made one diagram as a start example (in excalidraw, which allows us to export it and version it here as well):

![image](https://github.com/talkdai/dialog/assets/27077298/ef65f04d-8061-4fc0-a3e2-b4b4189706ab)

**Comment by lgabs** [comment]
Here is the .zip with the above image
[dialog-architecture.excalidraw.zip](https://github.com/user-attachments/files/15519125/dialog-architecture.excalidraw.zip)

**Comment by vmesel** [comment]
@lgabs thank you for the awesome diagram!

Wanna do a PR so we put this into the README.md and in the docs?

**Comment by lgabs** [comment]
Sure :)
