### ISSUE TITLE
Improve load_csv.py to use langchain's CSVLoader

### ISSUE THREAD

**Issue by lgabs** [talkdai/dialog#199]
Currently, [load_csv](https://github.com/talkdai/dialog/blob/main/src/load_csv.py) make the document embeddings using pandas to load the csv and making some preprocessing to assert necessary columns, builds a primary key with category/subcategory/question to compare with already present keys and keep only new ones, and then insert embeddings in the vectordb. 

However, langchain's already has many document loaders, including CSVLoader, which does not even use pandas, and maybe we could simplify our code using it without the pandas dependency here. The usage of a langchain's document loader goes in the direction of making a more flexible `load_csv` with langchain's components and also for a more generic approach for the other csv fields not embedded, which in langchain's terms are document _metadata_, and in its vectorstores integrations these metadata are stores typically as a jsonb field. In the future, we could use these metadata for better retrieval (e.g. filter some metadata when making the vectordb query) or custom context prompt creation (currently examples in [lcel](https://github.com/talkdai/dialog/blob/main/src/dialog/llm/agents/lcel.py#L60) and [default](https://github.com/talkdai/dialog/blob/main/src/dialog/llm/agents/default.py#L53) rags) in a more flexible way, allowing user specific metadata. For example, in a RAG about movies, metadata could be `director`, `actors`, `genre`. 

A quickstart to see the usage of CSVLoader is available in this [dialog fork](https://github.com/lgabs/dialog/blob/main/src/scripts/make_embeddings.py) file, which makes the same as `load_csv.py`, but not full compatible with dialog main due to the different vectordb approach. For the current state of dialog, the actual implementation would start with something like the following, but taking care of keeping current compatibility and maybe adding the metadata jsonb new field (for reference, here is the [langchain_postgres](https://github.com/langchain-ai/langchain-postgres/blob/main/langchain_postgres/vectorstores.py#L138)'s schema):

```python
import argparse
from typing import List

import hashlib

import csv
from sqlalchemy import text

from langchain_community.document_loaders.csv_loader import CSVLoader
from langchain_core.documents import Document

from dialog_lib.embeddings.generate import generate_embeddings
from dialog.llm.embeddings import EMBEDDINGS_LLM
from dialog_lib.db.models import CompanyContent
from dialog.db import get_session
from dialog.settings import Settings

import logging

logging.basicConfig(
    level=Settings().LOGGING_LEVEL,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
)

logger = logging.getLogger("make_embeddings")

session = next(get_session())
NECESSARY_COLS = ["category", "subcategory", "question", "content"]

def _get_csv_cols(path: str):
    with open(path) as f:
        reader = csv.DictReader(f)
        return reader.fieldnames

def load_csv_and_generate_embeddings(path, cleardb=False, embed_columns=("content",)):
    
    metadata_columns = [
        col for col in _get_csv_cols(path) if col not in embed_columns
    ]
    
    loader = CSVLoader(path, metadata_columns=metadata_columns)
    docs: List[Document] = loader.load()

    logger.info("Metadata columns: %s", metadata_columns)
    logger.info("Embedding columns: %s", embed_columns)
    logger.info("Glimpse over the first doc: %s", docs[0].page_content[:100])
    
    for col in NECESSARY_COLS:
        if col not in metadata_columns + embed_columns:
            raise Exception(f"Column {col} not found in {path}")

    # Create primary key column using category, subcategory, and question
    def add_document_pk(doc: Document) -> Document:
        pk = doc.metadata["category"] + doc.metadata["subcategory"] + doc.metadata["question"]
        doc.metadata["primary_key"] = hashlib.md5(pk.encode()).hexdigest()
        return doc
    docs: List[Document] = [add_document_pk(doc) for doc in docs]

    if cleardb:
        session.query(CompanyContent).delete()
        session.commit()

    # TODO: read from the vectorstore without pandas and return as List[Document]
    docs_in_db: List[Document] = ...
    existing_pks: List[str] =  [add_document_pk(doc).metadata["primary_key"] for doc in docs_in_db]

    # Filter df for keys present in df and not present in df_in_db
    docs_filtered: List[Document] = [doc for doc in docs if doc.metadata["primary_key"] not in existing_pks]
    if len(docs_filtered) == 0:
        return
    for doc in docs_filtered:
        doc.pop('primary_key', None)

    print("Generating embeddings for new questions...")
    print("New questions:", len(docs_filtered))
    print("embed_columns: ", embed_columns)

    embedded_docs = generate_embeddings([doc.page_content for doc in docs_filtered], embedding_llm_instance=EMBEDDINGS_LLM)
    # TODO: write new embedding from the vectorstore with sqlalchemy
    for doc, embedding in zip(docs_filtered, embedded_docs):
        ...


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--path", type=str, required=False, default="./know.csv")
    parser.add_argument("--cleardb", action="store_true")
    parser.add_argument("--embed-columns", default="content")
    args = parser.parse_args()

    load_csv_and_generate_embeddings(
        args.path, args.cleardb, args.embed_columns.split(','))
       
```

**Comment by vmesel** [comment]
Thanks for making this discussion public @lgabs, we really need to move forward towards langchain's approach on document retrieval.

My only question is what should be the first change to start and make our format comply to langchain's.

**Comment by lgabs** [comment]
The smallest change I see is the snippet above, where pandas is not used, the code uses CSVLoader and terminology of metadata, but postgres models could still be the same. The "..." I've left would be the actual interface from Langchain Document object qnd and objects read from db using sqlachemy ("read from db ->list of Documents" and "list of Documents" -> write in db" operations)

**Comment by lgabs** [comment]
This  #200 WIP PR shows the idea, I've managed to make the two operations I've said above and it's now working. Take a look @vmesel.
