### ISSUE TITLE
OpenAI sensitive data is putting `XXXXXXXXXX`

### ISSUE THREAD

**Issue by avelino** [talkdai/dialog#20]
**QA:** vc tem whatsapp?
**answer:** Peço desculpas pela confusão. O número de WhatsApp da Buser é XXXXXXXXXX. Sinta-se à vontade para entrar em contato conosco por lá. Estamos aqui para ajudar!

![Screenshot 2023-11-18 at 10 44 39](https://github.com/talkdai/dialog/assets/31996/4ed60f73-7f99-4a15-8ca0-4653a9c1e768)

**Comment by vmesel** [comment]
this is solved with the new categories approach on the TOML file.
