### ISSUE TITLE
 TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'

### ISSUE THREAD

**Issue by alexfilothodoros** [talkdai/dialog#207]
Hi.
I've been trying to run  docker-compose up for the first time.
The process is stuck when a TypeError appears.

Any ideas why this is happening?

`[+] Running 2/0
 ✔ Container dialog-db-1      Created                                                                                                                                                                            0.0s
 ✔ Container dialog-dialog-1  Created                                                                                                                                                                            0.0s
Attaching to db-1, dialog-1
db-1      |
db-1      | PostgreSQL Database directory appears to contain a database; Skipping initialization
db-1      |
db-1      | 2024-06-08 14:48:16.139 UTC [1] LOG:  starting PostgreSQL 15.7 (Debian 15.7-1.pgdg120+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
db-1      | 2024-06-08 14:48:16.139 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db-1      | 2024-06-08 14:48:16.139 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db-1      | 2024-06-08 14:48:16.140 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1      | 2024-06-08 14:48:16.142 UTC [29] LOG:  database system was shut down at 2024-06-08 14:48:14 UTC
db-1      | 2024-06-08 14:48:16.145 UTC [1] LOG:  database system is ready to accept connections
dialog-1  | Traceback (most recent call last):
dialog-1  |   File "/usr/local/bin/alembic", line 8, in <module>
dialog-1  |     sys.exit(main())
dialog-1  |              ^^^^^^
dialog-1  |   File "/usr/local/lib/python3.12/site-packages/alembic/config.py", line 641, in main
dialog-1  |     CommandLine(prog=prog).main(argv=argv)
dialog-1  |   File "/usr/local/lib/python3.12/site-packages/alembic/config.py", line 631, in main
dialog-1  |     self.run_cmd(cfg, options)
dialog-1  |   File "/usr/local/lib/python3.12/site-packages/alembic/config.py", line 608, in run_cmd
dialog-1  |     fn(
dialog-1  |   File "/usr/local/lib/python3.12/site-packages/alembic/command.py", line 403, in upgrade
dialog-1  |     script.run_env()
dialog-1  |   File "/usr/local/lib/python3.12/site-packages/alembic/script/base.py", line 583, in run_env
dialog-1  |     util.load_python_file(self.dir, "env.py")
dialog-1  |   File "/usr/local/lib/python3.12/site-packages/alembic/util/pyfiles.py", line 95, in load_python_file
dialog-1  |     module = load_module_py(module_id, path)
dialog-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dialog-1  |   File "/usr/local/lib/python3.12/site-packages/alembic/util/pyfiles.py", line 113, in load_module_py
dialog-1  |     spec.loader.exec_module(module)  # type: ignore
dialog-1  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dialog-1  |   File "<frozen importlib._bootstrap_external>", line 995, in exec_module
dialog-1  |   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
dialog-1  |   File "/app/src/dialog/migrations/env.py", line 7, in <module>
dialog-1  |     from dialog_lib.db.models import Base
dialog-1  |   File "/usr/local/lib/python3.12/site-packages/dialog_lib/db/__init__.py", line 2, in <module>
dialog-1  |     from .memory import (
dialog-1  |   File "/usr/local/lib/python3.12/site-packages/dialog_lib/db/memory.py", line 3, in <module>
dialog-1  |     from langchain_postgres import PostgresChatMessageHistory
dialog-1  |   File "/usr/local/lib/python3.12/site-packages/langchain_postgres/__init__.py", line 9, in <module>
dialog-1  |     from langchain_postgres.vectorstores import PGVector
dialog-1  |   File "/usr/local/lib/python3.12/site-packages/langchain_postgres/vectorstores.py", line 29, in <module>
dialog-1  |     from langchain_core.documents import Document
dialog-1  |   File "/usr/local/lib/python3.12/site-packages/langchain_core/documents/__init__.py", line 6, in <module>
dialog-1  |     from langchain_core.documents.compressor import BaseDocumentCompressor
dialog-1  |   File "/usr/local/lib/python3.12/site-packages/langchain_core/documents/compressor.py", line 6, in <module>
dialog-1  |     from langchain_core.callbacks import Callbacks
dialog-1  |   File "/usr/local/lib/python3.12/site-packages/langchain_core/callbacks/__init__.py", line 22, in <module>
dialog-1  |     from langchain_core.callbacks.manager import (
dialog-1  |   File "/usr/local/lib/python3.12/site-packages/langchain_core/callbacks/manager.py", line 29, in <module>
dialog-1  |     from langsmith.run_helpers import get_run_tree_context
dialog-1  |   File "/usr/local/lib/python3.12/site-packages/langsmith/run_helpers.py", line 40, in <module>
dialog-1  |     from langsmith import client as ls_client
dialog-1  |   File "/usr/local/lib/python3.12/site-packages/langsmith/client.py", line 52, in <module>
dialog-1  |     from langsmith import env as ls_env
dialog-1  |   File "/usr/local/lib/python3.12/site-packages/langsmith/env/__init__.py", line 3, in <module>
dialog-1  |     from langsmith.env._runtime_env import (
dialog-1  |   File "/usr/local/lib/python3.12/site-packages/langsmith/env/_runtime_env.py", line 10, in <module>
dialog-1  |     from langsmith.utils import get_docker_compose_command
dialog-1  |   File "/usr/local/lib/python3.12/site-packages/langsmith/utils.py", line 31, in <module>
dialog-1  |     from langsmith import schemas as ls_schemas
dialog-1  |   File "/usr/local/lib/python3.12/site-packages/langsmith/schemas.py", line 69, in <module>
dialog-1  |     class Example(ExampleBase):
dialog-1  |   File "/usr/local/lib/python3.12/site-packages/pydantic/v1/main.py", line 286, in __new__
dialog-1  |     cls.__try_update_forward_refs__()
dialog-1  |   File "/usr/local/lib/python3.12/site-packages/pydantic/v1/main.py", line 807, in __try_update_forward_refs__
dialog-1  |     update_model_forward_refs(cls, cls.__fields__.values(), cls.__config__.json_encoders, localns, (NameError,))
dialog-1  |   File "/usr/local/lib/python3.12/site-packages/pydantic/v1/typing.py", line 554, in update_model_forward_refs
dialog-1  |     update_field_forward_refs(f, globalns=globalns, localns=localns)
dialog-1  |   File "/usr/local/lib/python3.12/site-packages/pydantic/v1/typing.py", line 520, in update_field_forward_refs
dialog-1  |     field.type_ = evaluate_forwardref(field.type_, globalns, localns or None)
dialog-1  |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dialog-1  |   File "/usr/local/lib/python3.12/site-packages/pydantic/v1/typing.py", line 66, in evaluate_forwardref
dialog-1  |     return cast(Any, type_)._evaluate(globalns, localns, set())
dialog-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dialog-1  | TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
dialog-1  | Traceback (most recent call last):
dialog-1  |   File "/app/src/load_csv.py", line 6, in <module>
dialog-1  |     from langchain_community.document_loaders.csv_loader import CSVLoader
dialog-1  |   File "/usr/local/lib/python3.12/site-packages/langchain_community/document_loaders/csv_loader.py", line 6, in <module>
dialog-1  |     from langchain_core.documents import Document
dialog-1  |   File "/usr/local/lib/python3.12/site-packages/langchain_core/documents/__init__.py", line 6, in <module>
dialog-1  |     from langchain_core.documents.compressor import BaseDocumentCompressor
dialog-1  |   File "/usr/local/lib/python3.12/site-packages/langchain_core/documents/compressor.py", line 6, in <module>
dialog-1  |     from langchain_core.callbacks import Callbacks
dialog-1  |   File "/usr/local/lib/python3.12/site-packages/langchain_core/callbacks/__init__.py", line 22, in <module>
dialog-1  |     from langchain_core.callbacks.manager import (
dialog-1  |   File "/usr/local/lib/python3.12/site-packages/langchain_core/callbacks/manager.py", line 29, in <module>
dialog-1  |     from langsmith.run_helpers import get_run_tree_context
dialog-1  |   File "/usr/local/lib/python3.12/site-packages/langsmith/run_helpers.py", line 40, in <module>
dialog-1  |     from langsmith import client as ls_client
dialog-1  |   File "/usr/local/lib/python3.12/site-packages/langsmith/client.py", line 52, in <module>
dialog-1  |     from langsmith import env as ls_env
dialog-1  |   File "/usr/local/lib/python3.12/site-packages/langsmith/env/__init__.py", line 3, in <module>
dialog-1  |     from langsmith.env._runtime_env import (
dialog-1  |   File "/usr/local/lib/python3.12/site-packages/langsmith/env/_runtime_env.py", line 10, in <module>
dialog-1  |     from langsmith.utils import get_docker_compose_command
dialog-1  |   File "/usr/local/lib/python3.12/site-packages/langsmith/utils.py", line 31, in <module>
dialog-1  |     from langsmith import schemas as ls_schemas
dialog-1  |   File "/usr/local/lib/python3.12/site-packages/langsmith/schemas.py", line 69, in <module>
dialog-1  |     class Example(ExampleBase):
dialog-1  |   File "/usr/local/lib/python3.12/site-packages/pydantic/v1/main.py", line 286, in __new__
dialog-1  |     cls.__try_update_forward_refs__()
dialog-1  |   File "/usr/local/lib/python3.12/site-packages/pydantic/v1/main.py", line 807, in __try_update_forward_refs__
dialog-1  |     update_model_forward_refs(cls, cls.__fields__.values(), cls.__config__.json_encoders, localns, (NameError,))
dialog-1  |   File "/usr/local/lib/python3.12/site-packages/pydantic/v1/typing.py", line 554, in update_model_forward_refs
dialog-1  |     update_field_forward_refs(f, globalns=globalns, localns=localns)
dialog-1  |   File "/usr/local/lib/python3.12/site-packages/pydantic/v1/typing.py", line 520, in update_field_forward_refs
dialog-1  |     field.type_ = evaluate_forwardref(field.type_, globalns, localns or None)
dialog-1  |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dialog-1  |   File "/usr/local/lib/python3.12/site-packages/pydantic/v1/typing.py", line 66, in evaluate_forwardref
dialog-1  |     return cast(Any, type_)._evaluate(globalns, localns, set())
dialog-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dialog-1  | TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
dialog-1  | INFO:     Will watch for changes in these directories: ['/app/src']
dialog-1  | INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
dialog-1  | INFO:     Started reloader process [1] using WatchFiles
dialog-1  | Process SpawnProcess-1:
dialog-1  | Traceback (most recent call last):
dialog-1  |   File "/usr/local/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
dialog-1  |     self.run()
dialog-1  |   File "/usr/local/lib/python3.12/multiprocessing/process.py", line 108, in run
dialog-1  |     self._target(*self._args, **self._kwargs)
dialog-1  |   File "/usr/local/lib/python3.12/site-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
dialog-1  |     target(sockets=sockets)
dialog-1  |   File "/usr/local/lib/python3.12/site-packages/uvicorn/server.py", line 61, in run
dialog-1  |     return asyncio.run(self.serve(sockets=sockets))
dialog-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dialog-1  |   File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run
dialog-1  |     return runner.run(main)
dialog-1  |            ^^^^^^^^^^^^^^^^
dialog-1  |   File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
dialog-1  |     return self._loop.run_until_complete(task)
dialog-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dialog-1  |   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
dialog-1  |   File "/usr/local/lib/python3.12/site-packages/uvicorn/server.py", line 68, in serve
dialog-1  |     config.load()
dialog-1  |   File "/usr/local/lib/python3.12/site-packages/uvicorn/config.py", line 467, in load
dialog-1  |     self.loaded_app = import_from_string(self.app)
dialog-1  |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dialog-1  |   File "/usr/local/lib/python3.12/site-packages/uvicorn/importer.py", line 21, in import_from_string
dialog-1  |     module = importlib.import_module(module_str)
dialog-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dialog-1  |   File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
dialog-1  |     return _bootstrap._gcd_import(name[level:], package, level)
dialog-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dialog-1  |   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
dialog-1  |   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
dialog-1  |   File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
dialog-1  |   File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
dialog-1  |   File "<frozen importlib._bootstrap_external>", line 995, in exec_module
dialog-1  |   File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
dialog-1  |   File "/app/src/main.py", line 10, in <module>
dialog-1  |     from dialog.routers import api_router, open_ai_api_router
dialog-1  |   File "/app/src/dialog/routers/__init__.py", line 1, in <module>
dialog-1  |     from .dialog import *
dialog-1  |   File "/app/src/dialog/routers/dialog.py", line 9, in <module>
dialog-1  |     from dialog.llm import process_user_message, add_langserve_routes
dialog-1  |   File "/app/src/dialog/llm/__init__.py", line 6, in <module>
dialog-1  |     from dialog_lib.agents.abstract import AbstractLLM
dialog-1  |   File "/usr/local/lib/python3.12/site-packages/dialog_lib/agents/__init__.py", line 1, in <module>
dialog-1  |     from .abstract import *
dialog-1  |   File "/usr/local/lib/python3.12/site-packages/dialog_lib/agents/abstract.py", line 1, in <module>
dialog-1  |     from langchain.prompts import ChatPromptTemplate, MessagesPlaceholder
dialog-1  |   File "/usr/local/lib/python3.12/site-packages/langchain/prompts/__init__.py", line 32, in <module>
dialog-1  |     from langchain_core.example_selectors import (
dialog-1  |   File "/usr/local/lib/python3.12/site-packages/langchain_core/example_selectors/__init__.py", line 6, in <module>
dialog-1  |     from langchain_core.example_selectors.length_based import (
dialog-1  |   File "/usr/local/lib/python3.12/site-packages/langchain_core/example_selectors/length_based.py", line 6, in <module>
dialog-1  |     from langchain_core.prompts.prompt import PromptTemplate
dialog-1  |   File "/usr/local/lib/python3.12/site-packages/langchain_core/prompts/__init__.py", line 27, in <module>
dialog-1  |     from langchain_core.prompts.base import (
dialog-1  |   File "/usr/local/lib/python3.12/site-packages/langchain_core/prompts/base.py", line 22, in <module>
dialog-1  |     from langchain_core.output_parsers.base import BaseOutputParser
dialog-1  |   File "/usr/local/lib/python3.12/site-packages/langchain_core/output_parsers/__init__.py", line 15, in <module>
dialog-1  |     from langchain_core.output_parsers.base import (
dialog-1  |   File "/usr/local/lib/python3.12/site-packages/langchain_core/output_parsers/base.py", line 18, in <module>
dialog-1  |     from langchain_core.language_models import LanguageModelOutput
dialog-1  |   File "/usr/local/lib/python3.12/site-packages/langchain_core/language_models/__init__.py", line 25, in <module>
dialog-1  |     from langchain_core.language_models.base import (
dialog-1  |   File "/usr/local/lib/python3.12/site-packages/langchain_core/language_models/base.py", line 75, in <module>
dialog-1  |     class BaseLanguageModel(
dialog-1  |   File "/usr/local/lib/python3.12/site-packages/pydantic/v1/main.py", line 286, in __new__
dialog-1  |     cls.__try_update_forward_refs__()
dialog-1  |   File "/usr/local/lib/python3.12/site-packages/pydantic/v1/main.py", line 807, in __try_update_forward_refs__
dialog-1  |     update_model_forward_refs(cls, cls.__fields__.values(), cls.__config__.json_encoders, localns, (NameError,))
dialog-1  |   File "/usr/local/lib/python3.12/site-packages/pydantic/v1/typing.py", line 554, in update_model_forward_refs
dialog-1  |     update_field_forward_refs(f, globalns=globalns, localns=localns)
dialog-1  |   File "/usr/local/lib/python3.12/site-packages/pydantic/v1/typing.py", line 520, in update_field_forward_refs
dialog-1  |     field.type_ = evaluate_forwardref(field.type_, globalns, localns or None)
dialog-1  |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dialog-1  |   File "/usr/local/lib/python3.12/site-packages/pydantic/v1/typing.py", line 66, in evaluate_forwardref
dialog-1  |     return cast(Any, type_)._evaluate(globalns, localns, set())
dialog-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dialog-1  | TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'`

**Comment by vmesel** [comment]
@alexfilothodoros just updated the docker image, should be good to go! Let me know if the problem pops up again!

**Comment by alexfilothodoros** [comment]
Hi @vmesel 
Thanks for that but I still get the error.

**Comment by vmesel** [comment]
@alexfilothodoros can you force the rebuild of the docker image with `docker-compose up --build` command?

**Comment by alexfilothodoros** [comment]
@vmesel that did the trick! Thanks :)
