### ISSUE TITLE
[Documentation] image preview not available

### ISSUE THREAD

**Issue by alexfilothodoros** [talkdai/dialog#208]
Here

https://dev.to/vmesel/deploy-your-own-chatgpt-in-5-minutes-5d41

The image preview after the title "PGVector - Our first service"  is not displayed
<img width="802" alt="Screenshot 2024-06-08 at 16 55 20" src="https://github.com/talkdai/dialog/assets/6419847/14fbf481-292c-4052-a01a-c99ada33a71c">

**Comment by vmesel** [comment]
@alexfilothodoros strange, here it is up and running... Can you send me your browser (which browser you are using, the version and any relevant extensions)?

Here it shows normally:

<img width="1141" alt="image" src="https://github.com/talkdai/dialog/assets/4984147/f59750a9-346a-4c5c-a3ca-02313de61870">

**Comment by alexfilothodoros** [comment]
Actually it's OK now!

For the record I am using Safari Version 17.5 (19618.2.12.11.6).
