### ISSUE TITLE
Log Injection

### ISSUE THREAD

**Issue by avelino** [talkdai/dialog#209]
since it is possible to inject information into the log (stdout), this is not secure

https://github.com/talkdai/dialog/blob/941ca28f851d4cbd56e875afa88631b89418fb6f/src/dialog/routers/dialog.py#L38-L38

https://github.com/talkdai/dialog/blob/941ca28f851d4cbd56e875afa88631b89418fb6f/src/dialog/routers/openai.py#L47-L47

## References

OWASP: [Log Injection](https://owasp.org/www-community/attacks/Log_Injection).
Common Weakness Enumeration: [CWE-117](https://cwe.mitre.org/data/definitions/117.html).

**Tracking issue for:**

- [ ] https://github.com/talkdai/dialog/security/code-scanning/1
- [ ] https://github.com/talkdai/dialog/security/code-scanning/2

**Comment by vmesel** [comment]
@avelino is this a vulnerability? I've seen it on the scan, but as it's not identifiable, I thought it wasn't worth fixing it sometime.

**Comment by vmesel** [comment]
Fixed!

**Comment by avelino** [comment]
> Fixed!

@vmesel in which pr or commit?
we need to be easy to work with, for people to get to the solution in a simple way - the premise of being an open source solution

**Comment by vmesel** [comment]
Sure @avelino, you are totally right!

Commits are:

[Hotfix: Langchain version bumping for fixing](https://github.com/talkdai/dialog/commit/25cc1ba63ab4706dece46387474992bd95cbcd26) https://github.com/advisories/GHSA-3hjh-jh2h-vrg6 [- bumping dialog-lib to 0.0.1.19](https://github.com/talkdai/dialog/commit/25cc1ba63ab4706dece46387474992bd95cbcd26)

[Bump urllib3 from 2.2.1 to 2.2.2 in the pip group across 1 directory](https://github.com/talkdai/dialog/commit/66b425092345490e7247e239ec7388a3b49c6c0f)

[hotfix: Removes log injection vulnerability](https://github.com/talkdai/dialog/commit/6651d1a14d87c101180b21008226928c500600b7)
