### ISSUE TITLE
access to the database should avoid sessions to be left open

### ISSUE THREAD

**Issue by lgabs** [talkdai/dialog#213]
Some parts of database access are not controlling the ending of sessions, I think [this one in dialog-lib](https://github.com/talkdai/dialog-lib/blob/d92482eb0743412100f007ef2a9c1b6923b6a85e/dialog_lib/db/memory.py#L67) is an example. If the user of that function `generate_memory_instance`(like [that example](https://github.com/talkdai/dialog-lib/blob/d92482eb0743412100f007ef2a9c1b6923b6a85e/samples/openai/main.py#L12)) does not close the session, It may lead to problems related to the limits of the sql alchemy pool of connections. I think there are other parts of the lib with this problems as well, we'd have to investigate better.

**Possible solution**
A possible solution could use context management inside functions that access the database to avoid this, removing this session managemente from the user interface (in the open ai example above, the user wouldn't need to instantiate a db session).

**Comment by lgabs** [comment]
Some other parts I've seen the session being used in a way that I think the session could be left open are:
- [the retriever function](https://github.com/talkdai/dialog-lib/blob/d92482eb0743412100f007ef2a9c1b6923b6a85e/dialog_lib/embeddings/generate.py#L32), where, for example, the [default](https://github.com/talkdai/dialog/blob/14e19f619155a710de4c350c0a78adc1942ae9d6/src/dialog/llm/agents/default.py#L22) LLM_CLASS instantiate the session directly
- the retriever as a langchain runnable for LCEL case, [here](https://github.com/talkdai/dialog/blob/14e19f619155a710de4c350c0a78adc1942ae9d6/src/dialog/llm/agents/lcel.py#L56)

**Comment by vmesel** [comment]
Interesting, this can cause several problems on production, but I honestly don't know if we should pass on a session or inject a dependency to solve this issue.
