### ISSUE TITLE
Chat history not being passed into default DialogLLM when using Open WebUI

### ISSUE THREAD

**Issue by wdec** [talkdai/dialog#215]
**Describe the bug**
When using the default dialogLLM, the retrieved chat history is not passed into the actual API call.

**To Reproduce**
1. Start with default settings
2. Make query via a POST call to /chat/{chat_id} (already visible at this stage)
3. Repeat the POST, asking for the last query

**Expected behavior**
chat history should be passed

**Additional context**
The problem appears to be in the lower dialog-lib package (tried both 0.0.2.0 and 0.0.1.19) that's missing the chat_history, or alternatively the withChatHistory instance isn't used on the dialogLLM

ai_message = llm_class.invoke(
    {
        "input": message,
        "chat_history": chat_history  # Assuming chat_history is a variable holding the history
    },

**Comment by vmesel** [comment]
Hey @wdec, thank you for reporting this bug. Have you used the same session id on both requests? How was the request done, was it through Open WebUI or cURL?

**Comment by wdec** [comment]
> Hey @wdec, thank you for reporting this bug. Have you used the same session id on both requests? How was the request done, was it through Open WebUI or cURL?

Hi. Yes, used the same session id. The history is correctly updated in the DB and all. BTW The problem does NOT happen when using the lcel agent with the lang chain style. I used the open WebUI.

**Comment by vmesel** [comment]
Oh! Got it! So whenever you use Open WebUI, there is still some work to do regarding session's memory there.

Open WebUI use the base for the /ask endpoint.

I'm quite sure we can address this by generating a single session id that's usable in Open WebUI

**Comment by vmesel** [comment]
Hey @wdec, thank you for reporting this bug! I was able to work on a fix for it and would love you to test it and see if it works for you. The branch with the fix is `fix/openwebui-session-management`.

**Comment by wdec** [comment]
Hi. Well, the problem is not in using the openweb ui, which worked fine, but rather that with the /chat/{chat_id} DialogLLM endpoint the history is not sent to the LLM. The branch you indicate still has that issue.

**Comment by vmesel** [comment]
@wdec Going to verify it! Thanks for more context

**Comment by vmesel** [comment]
@wdec some updates: It looks like the code itself was ok, but for some reason, the chat history wasn't being used as a part of the answer.

I've updated the branch `fix/openwebui-session-management` with the proper history management. I would love you to test it and check if it solves your issue.

In the latest commit I've added a line to the toml, so if you are using a custom toml file with your prompt instead of the default provided one, you need to add the `[prompt.history_header]` session.

To reproduce the behavior that I've had locally with this branch you will run the following cURLs:


```bash
$ curl -X 'POST' \
  'http://localhost:8000/session' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "chat_id": "test_session"
}'

# Expected output: {"chat_id":"test_session"}

curl -X 'POST' \
  'http://localhost:8000/chat/test_session' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "message": "My name is vinnie!"
}'

# Expected output: {"message":"Hi Vinnie! It's so nice to meet you. How are you doing today? If you have any questions or need help with something, feel free to ask. I'll do my best to assist you, even though I might not know everything about the topic."}

curl -X 'POST' \
  'http://localhost:8000/chat/test_session' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "message": "What is my name?"
}'

# Expected output: {"message":"Your name is Vinnie! How are you doing today? If you have any questions or need assistance with something, I'm here to help."}
```

**Comment by wdec** [comment]
Thanks
