### ISSUE TITLE
psycopg2-binary is not advised to be used for production environment

### ISSUE THREAD

**Issue by lgabs** [talkdai/dialog#217]
dialog-lib [has a dependency](https://github.com/talkdai/dialog-lib/blob/5b07ec6080b296438a8d001323ffb3130957bebe/pyproject.toml#L16) for psycopg2-binary, which is not advised to be used for production environment as the [official documentation](https://www.psycopg.org/docs/install.html#psycopg-vs-psycopg-binary) warns. Maybe it would be better to keep the library functional without it. For reference, langchain_postgres depends on psycopg3 explicitly.

**Comment by vmesel** [comment]
@lgabs I'm closing this issue since it's regarding the library, I'll reopen a new one on the dependency for dialog itself.
