### ISSUE TITLE
hallucination: when asking a question outside the content base you are responding to, we must limit

### ISSUE THREAD

**Issue by avelino** [talkdai/dialog#33]
**QA:** how to make carrot cake?
**answer:** To make a carrot cake, you will need the following ingredients: grated carrots, flour, sugar, eggs, vegetable oil, baking powder, baking soda, cinnamon, and salt. Mix all the dry ingredients together in one bowl, and the wet ingredients in another. Then, gradually add the dry mixture to the wet mixture, stirring until well combined. Pour the batter into a greased cake pan and bake in a preheated oven at 350°F (175°C) for about 30-35 minutes, or until a toothpick inserted into the center comes out clean. Let it cool before frosting with cream cheese frosting. Enjoy!

if the knowledge base is about a subject that has how to prepare cake with the ingredient, it's OK to give a cake recipe using the ingredient that the knowledge base has, but if it's a bus company and the knowledge base has nothing related to carrot cake, **I'd expect an answer along those lines:**

oops, I think you're asking a question that's way out of the context of a service, is there anything else I can help you with?

**Comment by lgabs** [comment]
I think this approach is good to avoid passing the prompt to the llm resolve. In addition, an approach that worked for me before is to add to the prompt template instructions that if the question can not be answered using the given content, than the assistant must answer some default phrase like you've shown.
