### ISSUE TITLE
`process_user_intent`: this is very logical

### ISSUE THREAD

**Issue by avelino** [talkdai/dialog#46]
`llm/__init__` needs to be refactored, thinking about the API and how it will be consumed, removing as much cognitive load as possible (isolating responsibilities).

**Comment by vmesel** [comment]
We need to make the LLM instance a class, so we can make it extensible via plugins. I'm going to think on a structure to do that, so we can make it extensible on the settings.py.

Also, if the new LLM needs more parameters, we need to be able to fetch them from the settings.py or environment variable. I dont know which is the best approach, but its doable in both ways.

**Comment by vmesel** [comment]
Closed by #80, and may require some changes, but its better than it was
