### ISSUE TITLE
Suggest the "data" folder to store .toml and knowledge base

### ISSUE THREAD

**Issue by lgabs** [talkdai/dialog#48]
In the project's root directory, should we indicate in the README that .toml and the knowledge base (.csv) should be in a `data/` folder? It's already ignored by [.gitignore](https://github.com/talkdai/dialog/blob/main/.gitignore#L161) to avoid their versioning.

**Comment by vmesel** [comment]
@lgabs we can suggest it in the README for sure, but its not a must to be there. The user can use another structure for storing their data.
