### ISSUE TITLE
Add setup for dev container 

### ISSUE THREAD

**Issue by lgabs** [talkdai/dialog#52]
Dev Container is very helpful for those who prefer VS Code :)

**Comment by vmesel** [comment]
@lgabs can you send us an example on how to use a Dev Container? Never used it before on VSCode.

**Comment by lgabs** [comment]
A made a simple example referencing the Dockerfile, but with the usage of docker compose I'm not sure how the config should be to make a good setup for dev, since [it seems](https://stackoverflow.com/questions/67773973/how-to-run-docker-compose-inside-vs-code-devcontainer) that vs code can only use one service as the "workspace" for the IDE. Maybe @avelino can help here.

```
{
	"name": "Existing Dockerfile",
	"build": {
		"context": "..",
		"dockerfile": "../Dockerfile"
	}
}
```

https://code.visualstudio.com/docs/devcontainers/containers#_getting-started
