### ISSUE TITLE
append memory to the prompt should be optional, is added by default

### ISSUE THREAD

**Issue by avelino** [talkdai/dialog#64]
**related:** #47

The longer the prompt, the slower OpenAI's response time.
Not in all cases do we want to pass all the session memory to the prompt

**I'm thinking of two solutions in configuration (`toml`):**

- memory in prompt
- last X messages at the prompt (not the entire history)

**Comment by walison17** [comment]
We can use `ConversationBufferWindowMemory` and make the window size configurable via settings
